name: Type Check

on:
  pull_request:
  push:
    branches:
      - main
      - development

jobs:
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install bun
        run: npm i -g bun
      - name: Install dependencies
        run: bun install
      - name: Run typecheck
        run: bun tsc --noEmit
